### ISSUE TITLE
Can't install qt5-qtmultimedia-examples due to dependancy

### ISSUE THREAD

**Issue by DavidMcKenna** [bitwiseworks/qtmultimedia-os2#1]
Tried to install qt5-qtmultimedia-examples 5.15.2 using ANPM1.0.6, but get an error message that says:

"qt5-qtmultimedia-examples-5.15.2-1.oc00.pentium4 requires fftreal.dll"

Don't know what package might contain fftreal.dll - please advise.

**Comment by Tellie** [comment]
Hi David
Look ad https://github.com/bitwiseworks/rpm-issues/issues/17

**Comment by DavidMcKenna** [comment]
Thanks for the tip TeLLie...
